#!/bin/bash
case "$1" in
start)
echo "Starting backlight control"
/recalbox/scripts/backlight-control.py & &> /dev/null
;;
stop)
echo "Stopping backlight control"
killall -9 backlight-control.py &> /dev/null
;;
restart)
echo "Stopping backlight control"
killall -9 backlight-control.py &> /dev/null
echo "Starting backlight control"
/recalbox/scripts/backlight-control.py & &> /dev/null
;;
*)
echo "Usage: /etc/init.d/S99backlight-control {start|stop|restart}"
exit 1
;;
esac
exit 0
